set(${PROJECT_NAME}_VERSION_MAJOR 0)
message ("${PROJECT_NAME}_VERSION_MAJOR: ${${PROJECT_NAME}_VERSION_MAJOR}")

set(${PROJECT_NAME}_VERSION_MINOR 0)
message ("${PROJECT_NAME}_VERSION_MINOR: ${${PROJECT_NAME}_VERSION_MINOR}")

set(${PROJECT_NAME}_VERSION_PATCH 5)
message ("${PROJECT_NAME}_VERSION_PATCH: ${${PROJECT_NAME}_VERSION_PATCH}")

set(VERSION_STRING "${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_PATCH}")
