
set(${PROJECT_NAME}_VERSION_LIFETIME 1)
message ("${PROJECT_NAME}_VERSION_LIFETIME: ${${PROJECT_NAME}_VERSION_LIFETIME}")

set(${PROJECT_NAME}_VERSION_MAJOR 3)
message ("${PROJECT_NAME}_VERSION_MAJOR: ${${PROJECT_NAME}_VERSION_MAJOR}")

set(${PROJECT_NAME}_VERSION_MINOR 1)
message ("${PROJECT_NAME}_VERSION_MINOR: ${${PROJECT_NAME}_VERSION_MINOR}")

set(${PROJECT_NAME}_VERSION_RELEASE 1)
message ("${PROJECT_NAME}_VERSION_RELEASE: ${${PROJECT_NAME}_VERSION_RELEASE}")

set(VERSION_STRING "${${PROJECT_NAME}_VERSION_LIFETIME}.${${PROJECT_NAME}_VERSION_MAJOR}.${${PROJECT_NAME}_VERSION_MINOR}.${${PROJECT_NAME}_VERSION_RELEASE}")
